// * Category Types
export const CATEGORY_FETCH = "CATEGORY_FETCH";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_FAILURE = "CATEGORY_FETCH_FAILURE";

// * Products Types
export const PRODUCTS_FETCH = "PRODUCTS_FETCH";
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCTS_FETCH_FAILURE = "PRODUCTS_FETCH_FAILURE";

// * Product Types
export const PRODUCT_FETCH = "PRODUCT_FETCH";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

// * Slide Types
export const SLIDE_FETCH = "SLIDE_FETCH";
export const SLIDE_FETCH_SUCCESS = "SLIDE_FETCH_SUCCESS";
export const SLIDE_FETCH_FAILURE = "SLIDE_FETCH_FAILURE";

// * Favorite Types
export const FAVORITE_FETCH = "FAVORITE_FETCH";
export const FAVORITE_FETCH_SUCCESS = "FAVORITE_FETCH_SUCCESS";
export const FAVORITE_FETCH_FAILURE = "FAVORITE_FETCH_FAILURE";
export const FAVORITE_ADD = "FAVORITE_ADD";
